const RoutesString = {
  Error404: '/404',
  DashboardLayout: '/app',
  MainLayout: '/',
  Account: '/app/account',
  Customers: '/app/customers',
  Furniture: '/app/furniture',
  FurnitureTypeCreate: '/app/furniture-type/create',
  FurnitureCreate: '/app/furniture/create',
  WareHouseCreate: '/app/warehouse/create',
  WareHouseUpdate: '/app/warehouse/update/:id',

  FurnitureUpdate: '/app/furniture/update/:id',
  Dashboard: '/app/dashboard',
  Products: '/app/products',
  Foods: '/app/foods',
  MenuCreate: '/app/menu/create',
  FoodCreate: '/app/foods/create',
  FoodUpdate: '/app/foods/update/:id',
  Hotels: '/app/hotels',
  HotelCreate: '/app/hotels/create',
  HotelUpdate: '/app/hotels/update/:id',
  Employees: '/app/employees',
  Booking: '/app/booking/create',
  BookingList: '/app/booking',
  CheckInList: '/app/check-in-list',
  WorkingList: '/app/working',
  InventoryList: '/app/warehouse',
  WorkingHistoryList: '/app/working/:id',
  EmployeeCreate: '/app/employees/create',
  EmployeeUpdate: '/app/employees/update/:id',
  CustomerCreate: '/app/customers/create',
  CustomerUpdate: '/app/customers/update/:id',
  Rooms: '/app/rooms',
  RoomCreate: '/app/rooms/create',
  RoomTypeCreate: '/app/rooms-types/create',
  RoomUpdate: '/app/rooms/update/:id',
  RoomTypeUpdate: '/app/rooms-types/update/:id',
  RoomType: '/app/rooms-types',
  Accounts: '/app/accounts',
  AccountCreate: '/app/accounts/create',
  AccountUpdate: '/app/accounts/update/:id',
  Login: '/',
  Register: '/register',
  Orders: '/app/orders',
  OrderCreate: '/app/orders/create',
  OrderUpdate: '/app/orders/update/:id',
  CUSTOMER_CHECKIN: '/customers-check-in'
};

export default RoutesString;
